### ISSUE TITLE
DATABASE_URL in environment over-rides configuration

### ISSUE THREAD

**Issue by pramsey** [NYCPlanning/labs-postgis-preview#56]
This may be "by design" actually, since it makes it faster to switch databases, but it's a surprise if (as with me) you have a legacy DATABASE_URL lying around for other reasons. Feel free to close if this is expected behaviour.

**Comment by chriswhong** [comment]
Hadn't encountered this yet.  What do you suggest, using something other than `DATABASE_URL` in `.env`?

**Comment by pramsey** [comment]
Yeah, maybe a more specific ENV var to avoid collisions? Or maybe the whole point is to have one, so that all relevant apps do the right thing. It was just my personal surprise, all of a sudden this new app was complaining about not being able to connect to a database I dropped 6 months ago. Probably just best to close this out as a personal nit.
